object Versions {
    const val core = "1.7.0"
    const val compose = "1.1.1"
    const val activity = "1.4.0"
    const val coil = "2.1.0"
    const val lifeCycle = "2.4.1"
    const val navigation = "2.4.2"
    const val hiltNavigation = "1.0.0"
    const val hilt = "2.42"
    const val okhttp = "4.9.3"
    const val retrofit = "2.9.0"
    const val coroutines = "1.6.0"
    const val kotlin = "1.6.10"
    const val junit = "4.13.2"
    const val espresso = "3.4.0"
    const val junitKtx = "1.1.3"
}